db:
  active: False
  name: "ozone_tme_lcpbe"
  ip: "localhost"
  port: "8889"

method:
  method_family: "dft"
  method: "lc-pbe"
  basis_set: "def2-svp"
  program: "orca"

files:
  pathfinder:
    path: "./vizchemoton/resources/crn_pathfinder.json"
    mode: "read"
  reactions:
    path: "./vizchemoton/resources/reactions2.csv"
    mode: "read"
  compounds:
    path: "./vizchemoton/resources/compounds2.json"
    mode: "read"

output:
  file: "network.html"
  title: "Chemoton graph"
  verbose: True

graph:
  dist_adduct: 3.0
  size: [1400, 800]
  layout: "kamada_kawai"
  map_field: "degree"



